'use client'
import './globals.css'
import { Inter } from 'next/font/google'
import Script from 'next/script'
import Head from 'next/head'
const inter = Inter({ subsets: ['latin'] })
import "bootstrap/dist/css/bootstrap.min.css";
import Menubar from '@/Components/Navbar'
import { ThemeProvider } from 'next-themes'
// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body className={inter.className}>
        <Menubar />
        <Head>
          <link
            rel="stylesheet"
            type="text/css" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
          />
          <link
            rel="stylesheet"
            type="text/css"
            href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
          />
        </Head>
        <ThemeProvider enableSystem={true} attribute="class">
          {children}
        </ThemeProvider>
        <Script
          src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
          integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW"
          crossOrigin="anonymous"
        />
        <Script src="sweetalert2.all.min.js" />

      </body>
    </html>
  )
}
